a= 5
b = 2
c = a+b
print(f'Soma = {c}')
c = a - b
print(f'Subtração = {c}')
c = a* b
print(f'Multiplicação = {c}')
c = a/b
print(f'Divisão  = {c}')
c = a//b
print(f'Quociente da Divisão = {c}')
c= a%b
print(f'Resto da Divisão = {c}')
